// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // WSPR Beakon Documentation sidebar with individual tabs
  wspr_beacon: [
    'intro',
    'implementation-examples',
    'bill-of-materials',
    'assembly',
    'filters',
    'software-configuration',
    'lcd-encoder-usage',
    'frequency-calibration',
    'kit-options',
    'license-disclaimer',
  ],

  // Alternative auto-generated sidebar (commented out)
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
